//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace matritsa.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("matritsa.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generic.
        /// </summary>
        public static string _util_pluralForm {
            get {
                return ResourceManager.GetString("_util.pluralForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matritsa.
        /// </summary>
        public static string appName {
            get {
                return ResourceManager.GetString("appName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matritsa (alpha).
        /// </summary>
        public static string appNameAlpha {
            get {
                return ResourceManager.GetString("appNameAlpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matritsa (beta).
        /// </summary>
        public static string appNameBeta {
            get {
                return ResourceManager.GetString("appNameBeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code list (CSV):.
        /// </summary>
        public static string codeList {
            get {
                return ResourceManager.GetString("codeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string codeListBtn {
            get {
                return ResourceManager.GetString("codeListBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (not selected).
        /// </summary>
        public static string codeListNone {
            get {
                return ResourceManager.GetString("codeListNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} codes/page.
        /// </summary>
        public static string codesPerPage_Few {
            get {
                return ResourceManager.GetString("codesPerPage.Few", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} code/page.
        /// </summary>
        public static string codesPerPage_One {
            get {
                return ResourceManager.GetString("codesPerPage.One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} codes/page.
        /// </summary>
        public static string codesPerPage_Other {
            get {
                return ResourceManager.GetString("codesPerPage.Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open code list.
        /// </summary>
        public static string dlgOpenCode {
            get {
                return ResourceManager.GetString("dlgOpenCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open file.
        /// </summary>
        public static string dlgOpenFile {
            get {
                return ResourceManager.GetString("dlgOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save file.
        /// </summary>
        public static string dlgSaveFile {
            get {
                return ResourceManager.GetString("dlgSaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frame size cannot be larger than page size.
        /// </summary>
        public static string generateBlockedReasonFrameLarge {
            get {
                return ResourceManager.GetString("generateBlockedReasonFrameLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frame size cannot be smaller than code size.
        /// </summary>
        public static string generateBlockedReasonFrameSmall {
            get {
                return ResourceManager.GetString("generateBlockedReasonFrameSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a code list first.
        /// </summary>
        public static string generateBlockedReasonList {
            get {
                return ResourceManager.GetString("generateBlockedReasonList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code size cannot be larger than page size.
        /// </summary>
        public static string generateBlockedReasonMtrxLarge {
            get {
                return ResourceManager.GetString("generateBlockedReasonMtrxLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code size cannot be 0.
        /// </summary>
        public static string generateBlockedReasonMtrxZero {
            get {
                return ResourceManager.GetString("generateBlockedReasonMtrxZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page size cannot be 0.
        /// </summary>
        public static string generateBlockedReasonPageZero {
            get {
                return ResourceManager.GetString("generateBlockedReasonPageZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently unavailable.
        /// </summary>
        public static string generateBlockedReasonUnavailable {
            get {
                return ResourceManager.GetString("generateBlockedReasonUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not yet available.
        /// </summary>
        public static string generateBlockedReasonUnfinished {
            get {
                return ResourceManager.GetString("generateBlockedReasonUnfinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save file.
        /// </summary>
        public static string generateBtn {
            get {
                return ResourceManager.GetString("generateBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating file....
        /// </summary>
        public static string generateProcess {
            get {
                return ResourceManager.GetString("generateProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string generateProcessCancel {
            get {
                return ResourceManager.GetString("generateProcessCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating codes....
        /// </summary>
        public static string generateProcessLayout {
            get {
                return ResourceManager.GetString("generateProcessLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating pages....
        /// </summary>
        public static string generateProcessRender {
            get {
                return ResourceManager.GetString("generateProcessRender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating page {0}/{1}....
        /// </summary>
        public static string generateProcessRenderPage {
            get {
                return ResourceManager.GetString("generateProcessRenderPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print preferences:.
        /// </summary>
        public static string layoutParams {
            get {
                return ResourceManager.GetString("layoutParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code:.
        /// </summary>
        public static string layoutParamsCode {
            get {
                return ResourceManager.GetString("layoutParamsCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same as frame.
        /// </summary>
        public static string layoutParamsIgnore {
            get {
                return ResourceManager.GetString("layoutParamsIgnore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If enabled, every page will have the same size as the code frame. This should be enabled for label printers..
        /// </summary>
        public static string layoutParamsIgnoreDesc {
            get {
                return ResourceManager.GetString("layoutParamsIgnoreDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page:.
        /// </summary>
        public static string layoutParamsPage {
            get {
                return ResourceManager.GetString("layoutParamsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frame height.
        /// </summary>
        public static string matrixFrameHeight {
            get {
                return ResourceManager.GetString("matrixFrameHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frame width.
        /// </summary>
        public static string matrixFrameWidth {
            get {
                return ResourceManager.GetString("matrixFrameWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string matrixSize {
            get {
                return ResourceManager.GetString("matrixSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string optionsBtn {
            get {
                return ResourceManager.GetString("optionsBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string pageHeight {
            get {
                return ResourceManager.GetString("pageHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Padding.
        /// </summary>
        public static string pagePadding {
            get {
                return ResourceManager.GetString("pagePadding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string pageWidth {
            get {
                return ResourceManager.GetString("pageWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product codes - {0}.
        /// </summary>
        public static string pdfTitle {
            get {
                return ResourceManager.GetString("pdfTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string printPreviewBtn {
            get {
                return ResourceManager.GetString("printPreviewBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centimeters.
        /// </summary>
        public static string unitCentimeter {
            get {
                return ResourceManager.GetString("unitCentimeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cm.
        /// </summary>
        public static string unitCentimeterShort {
            get {
                return ResourceManager.GetString("unitCentimeterShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inches.
        /// </summary>
        public static string unitInch {
            get {
                return ResourceManager.GetString("unitInch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in.
        /// </summary>
        public static string unitInchShort {
            get {
                return ResourceManager.GetString("unitInchShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Millimeters.
        /// </summary>
        public static string unitMillimeter {
            get {
                return ResourceManager.GetString("unitMillimeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mm.
        /// </summary>
        public static string unitMillimeterShort {
            get {
                return ResourceManager.GetString("unitMillimeterShort", resourceCulture);
            }
        }
    }
}
